### ISSUE TITLE
python TLSv1.2 problem 

### ISSUE THREAD

**Issue by hobik** [arthurazs/python-tls#1]
I am using python 3.8 and below openSSL version:

>>> import ssl
>>> ssl.OPENSSL_VERSION
'OpenSSL 1.1.1f  31 Mar 2020'
>>> ssl.PROTOCOL_TLSv1_2
<_SSLMethod.PROTOCOL_TLSv1_2: 5>

I I try to use client.c example ith below lines:

```
context = SSLContext( ssl.PROTOCOL_TLSv1_2)
context.options |= ssl.OP_NO_SSLv3
context.options |= ssl.OP_NO_TLSv1
context.options |= ssl.OP_NO_TLSv1_1
context.load_verify_locations('cert.pem')

with create_connection((ip, port)) as client:
    with context.wrap_socket(client, server_hostname=hostname) as tls:
        print(f'Using {tls.version()}\n')
        tls.sendall(b'Hello world')
```

But again client.py send message with TLSv1 version I trace with Wireshark. How can I use TLSv1.2 on client.c ?

**Comment by arthurazs** [comment]
I ran your code and got TLSv1.2

![ssl version](https://user-images.githubusercontent.com/3771055/134920198-d43f100c-d038-462d-ba54-0eaa39cfa6e0.png)

![terminal](https://user-images.githubusercontent.com/3771055/134919843-00648759-d1aa-4fd4-90e4-1440b4174a11.png)

![wireshark](https://user-images.githubusercontent.com/3771055/134919861-d3983dfa-1d8d-4777-8280-3b928197eef5.png)

I can't help you any further, sorry
